### ISSUE TITLE
Licensing Clarification

### ISSUE THREAD

**Issue by rez10191** [zoranbosnjak/asterix-data#2]
Hello,

First of all, thank you for your work on these ASTERIX projects!

I'd like to understand the licensing of the output XML files this project produces.  As I'm sure you know, the input files utilized are converted from the json versions of your [asterix-specs](https://github.com/zoranbosnjak/asterix-specs) project.  My understanding is the underlying `.ast` source is licensed under the [3 clause BSD license](https://opensource.org/licenses/BSD-3-Clause).

I see that this project's source is available under the GPLv3 (as per [COPYING](https://github.com/zoranbosnjak/asterix-data/blob/master/COPYING) ). However, the repo includes checked in versions of the XML output the utility generates.  Does that imply output is also GPL licensed?  I don't think this is typically how the GPL works (see this [FAQ entry](https://www.gnu.org/licenses/gpl-faq.en.html#GPLOutput) ), but I wanted to bring up the potential issue here.

My goal would be to integrate these files to a fork of [asterix4py](https://github.com/filipjonckers/asterix4py) and make a pull request to that author for inclusion of the latest versions of the files.  I think this would be acceptable under the licenses involved, but I didn't want to mix GPL and MIT licensed code if I am mistaken.  

As a longer term fix, perhaps the output XML files should simply be omitted from this repo?  Or potentially additional licensing information could be added to the outputs?  I'd also imagine you have plans to integrate the XML generator with the new `asterix-specs` project as well on a rainy day.

Thanks again,
Richard Zuber

**Comment by zoranbosnjak** [comment]
@rez10191 I was not aware of 'asterix4py' project.  Thanks for pointing out. I am also including @filipjonckers to the discussion.

The generated xml files in this project (asterix-data) are present in the repository for historical reasons. But be aware that the files here are not compatible with 'asterix4py' xml format. So the potential licensing problems are not relevant for your case.

I belive your intention is already resolved in 'asterix' project with the same xml structure as 'asterix4py'. It too can reuse the definitions from `asterix-specs` project. I have just created this pull request, which should resolve your problem. The conversion script can be part of 'asterix4py' and you can adjust the licensing if necessary. Please have a look and let's have further discussion here:
https://github.com/filipjonckers/asterix4py/pull/6
